spring:
  config:
    import: optional:classpath:application-secret.yml

  security:
    oauth2:
      client:
        registration:
          google:
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: HH:mm:ss dd/MM/yyyy
  datasource:
    url: jdbc:postgresql://localhost:5432/eduhubvn
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          trust: "*"
          starttls:
            enable: true
            required: true
        auth: true
        starttls:
          enabled: true
        connection-timeout: 5000
        timeout: 3000
        write-timeout: 5000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
application:
  security:
    jwt:
      expired:
        access: 2000000
        refresh: 900000000

server:
  port: 8080
